import SwiftUI

struct FicheView: View {
    let speciesId: Int

    @Environment(\.repository) private var repository
    @State private var detail: SpeciesDetail?

    var body: some View {
        ScrollView {
            if let detail {
                VStack(alignment: .leading, spacing: 24) {
                    header(detail)
                    FicheSections(detail: detail)
                    gallery(detail)
                    attribution(detail)
                }
                .padding(.bottom, 32)
            } else {
                ProgressView().padding(.top, 80)
            }
        }
        .background(Theme.paper)
        .navigationTitle(detail?.species.displayName ?? "")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
            if let detail {
                ToolbarItem(placement: .topBarTrailing) {
                    FavoriteButton(speciesId: detail.species.id)
                }
                if let url = sourceURL(detail) {
                    ToolbarItem(placement: .topBarTrailing) {
                        ShareLink(item: url) {
                            Image(systemName: "square.and.arrow.up")
                        }
                    }
                }
            }
        }
        .task(id: speciesId) { detail = try? repository.detail(id: speciesId) }
    }

    /// Every `sourceUrl` in the shipped database parses (2 837 of 2 837 checked),
    /// but the database is regenerated by the scraper, so a bad row must degrade
    /// to a missing link rather than a crash.
    private func sourceURL(_ detail: SpeciesDetail) -> URL? {
        URL(string: detail.species.sourceUrl)
    }

    private func header(_ detail: SpeciesDetail) -> some View {
        VStack(alignment: .leading, spacing: 0) {
            if detail.species.photoCount > 0 {
                RemoteImage(.photo(speciesId: detail.species.id, position: 0))
                    .frame(height: 260)
                    .frame(maxWidth: .infinity)
                    .clipped()
            }
            Rectangle()
                .fill(Theme.phylum(detail.species.phylumId).base)
                .frame(height: 3)

            VStack(alignment: .leading, spacing: 8) {
                HStack(spacing: 10) {
                    PhylumBadge(phylumId: detail.species.phylumId, size: 34)
                    VStack(alignment: .leading, spacing: 2) {
                        Text(detail.species.displayName)
                            .font(.title2.bold())
                            .foregroundStyle(Theme.ink)
                        Text(detail.species.scientificName)
                            .font(.headline).italic()
                            .foregroundStyle(Theme.inkSoft)
                    }
                }
                // Kept around `badges(_:)` so the row scrolls instead of overflowing
                // at large Dynamic Type sizes (checked at AX3 by Task 7).
                ViewThatFits(in: .horizontal) {
                    badges(detail)
                    ScrollView(.horizontal, showsIndicators: false) { badges(detail) }
                }
            }
            .padding(.horizontal)
            .padding(.top, 14)
        }
    }

    private func badges(_ detail: SpeciesDetail) -> some View {
        HStack(spacing: 8) {
            // `.base` at low alpha, not `.tint`: blending a fixed colour over the
            // dynamic `Theme.paper` backdrop makes the composite itself dynamic — pale
            // in light, dark in dark — so `Theme.ink` stays legible on it in both
            // (`.tint` alone has no dark variant and dropped to ~1:1 against `Theme.ink`
            // once that flipped to near-white in dark mode; see Task 7 fix round).
            Badge(text: detail.group.name, background: Theme.phylum(detail.species.phylumId).base.opacity(0.15))
            // No status badge: « Publiée » on nearly every fiche is noise, and the
            // two that follow are the ones that matter under water.
            if detail.species.regulated { Badge(text: "Réglementée", background: Theme.signal.opacity(0.14)) }
            if detail.species.dangerous { Badge(text: "Dangereuse", background: Theme.signal.opacity(0.14)) }
        }
    }

    private func gallery(_ detail: SpeciesDetail) -> some View {
        Group {
            if detail.photos.count > 1 {
                VStack(alignment: .leading, spacing: 8) {
                    sectionTitle("Galerie").padding(.horizontal)
                    ScrollView(.horizontal, showsIndicators: false) {
                        HStack(spacing: 8) {
                            ForEach(detail.photos) { photo in
                                NavigationLink(value: Route.gallery(photos: detail.photos, position: photo.position)) {
                                    RemoteImage(.photo(speciesId: detail.species.id, position: photo.position))
                                        .frame(width: 110, height: 110)
                                        .clipShape(.rect(cornerRadius: 10))
                                }
                            }
                        }
                        .padding(.horizontal)
                    }
                }
            }
        }
    }

    private func attribution(_ detail: SpeciesDetail) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            Divider().overlay(Theme.rule)
            Text("Fiche et photos : DORIS / FFESSM. Tous droits réservés.")
            if let url = sourceURL(detail) {
                Link("Voir la fiche sur doris.ffessm.fr", destination: url)
            }
            if let updatedAt = detail.species.updatedAt {
                Text("Mise à jour le \(updatedAt)")
            }
        }
        .font(.footnote)
        .foregroundStyle(Theme.inkSoft)
        .padding(.horizontal)
    }
}
