import SwiftUI

struct FicheView: View {
    let speciesId: Int

    @Environment(\.repository) private var repository
    @State private var detail: SpeciesDetail?

    var body: some View {
        ScrollView {
            if let detail {
                VStack(alignment: .leading, spacing: 24) {
                    header(detail)
                    FicheSections(detail: detail)
                    gallery(detail)
                    attribution(detail)
                }
                .padding(.bottom, 32)
            } else {
                ProgressView().padding(.top, 80)
            }
        }
        .navigationTitle(detail?.species.commonName ?? "")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
            if let detail {
                ToolbarItem(placement: .topBarTrailing) {
                    FavoriteButton(speciesId: detail.species.id)
                }
                if let url = sourceURL(detail) {
                    ToolbarItem(placement: .topBarTrailing) {
                        ShareLink(item: url) {
                            Image(systemName: "square.and.arrow.up")
                        }
                    }
                }
            }
        }
        .task(id: speciesId) { detail = try? repository.detail(id: speciesId) }
    }

    /// Every `sourceUrl` in the shipped database parses (2 837 of 2 837 checked),
    /// but the database is regenerated by the scraper, so a bad row must degrade
    /// to a missing link rather than a crash.
    private func sourceURL(_ detail: SpeciesDetail) -> URL? {
        URL(string: detail.species.sourceUrl)
    }

    private func header(_ detail: SpeciesDetail) -> some View {
        VStack(alignment: .leading, spacing: 12) {
            if detail.species.photoCount > 0 {
                RemoteImage(.photo(speciesId: detail.species.id, position: 0))
                    .frame(height: 240)
                    .frame(maxWidth: .infinity)
                    .clipped()
            }

            VStack(alignment: .leading, spacing: 6) {
                Text(detail.species.commonName).font(.title2.bold())
                Text(detail.species.scientificName).font(.headline).italic().foregroundStyle(.secondary)

                ViewThatFits(in: .horizontal) {
                    badges(detail)
                    ScrollView(.horizontal, showsIndicators: false) { badges(detail) }
                }
            }
            .padding(.horizontal)
        }
    }

    private func badges(_ detail: SpeciesDetail) -> some View {
        HStack(spacing: 8) {
            Badge(text: detail.group.name, tint: .teal)
            Badge(text: detail.species.status.label, tint: .gray)
            if detail.species.regulated { Badge(text: "Réglementée", tint: .indigo) }
            if detail.species.dangerous { Badge(text: "Dangereuse", tint: .orange) }
        }
    }

    private func gallery(_ detail: SpeciesDetail) -> some View {
        Group {
            if detail.photos.count > 1 {
                VStack(alignment: .leading, spacing: 8) {
                    Text("Galerie").font(.headline).padding(.horizontal)
                    ScrollView(.horizontal, showsIndicators: false) {
                        HStack(spacing: 8) {
                            ForEach(detail.photos) { photo in
                                NavigationLink(value: Route.gallery(speciesId: detail.species.id, position: photo.position)) {
                                    RemoteImage(.photo(speciesId: detail.species.id, position: photo.position))
                                        .frame(width: 110, height: 110)
                                        .clipShape(.rect(cornerRadius: 10))
                                }
                            }
                        }
                        .padding(.horizontal)
                    }
                }
            }
        }
    }

    private func attribution(_ detail: SpeciesDetail) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            Divider()
            Text("Fiche et photos : DORIS / FFESSM. Tous droits réservés.")
            if let url = sourceURL(detail) {
                Link("Voir la fiche sur doris.ffessm.fr", destination: url)
            }
            if let updatedAt = detail.species.updatedAt {
                Text("Mise à jour le \(updatedAt)")
            }
        }
        .font(.footnote)
        .foregroundStyle(.secondary)
        .padding(.horizontal)
    }
}

struct Badge: View {
    let text: String
    let tint: Color

    var body: some View {
        Text(text)
            .font(.caption.weight(.medium))
            .padding(.horizontal, 8)
            .padding(.vertical, 4)
            .background(tint.opacity(0.15), in: .capsule)
            .foregroundStyle(tint)
    }
}
